### PR TITLE
Experimental  更新README

### PR DESCRIPTION
**Pull request by colin4124**
在README 增加了邮件列表的联系方式和补充了加入IRC的方式

### CODE REVIEW

**Comment by biergaizi** [comment]
No!

**Comment by biergaizi** [comment]
You may BREAK our code base. Make sure what are you doing before open a Pull Request. Why do you change it `locale/WeCase_zh_CN.ts`?

**Comment by biergaizi** [comment]
By the way, why don't you commit code directly? Pull Request is for a non-member who want to merge code into mainline.

**Comment by colin4124** [comment]
Sorry,I haven't the experience

**Pull request closed without merging**
